---
- name: Change the hostname to sample-hostname
  hosts: all
  gather_facts: false
  tasks: 
    - psexec:
      executable: cmd.exe
      arguments: WMIC computersystem where caption='v-win10' rename win10awx
