---
- name:  Zmiana nazwy hosta
  hosts: all
  gather_facts: false
  tasks:
     - name: Zmiana nazwy hosta
        win_hostname:
        name: awxwin10
        
    - win_reboot:
      when: result.reboot_required