---
- name: Change the hostname to sample-hostname
  hosts: all
  gather_facts: false
  win_hostname:
    name: sample-hostname
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required