---
- name: Change the hostname to sample-hostname
  hosts: all
  gather_facts: false
  tasks: 
    - win_hostname: v-win10
      name: sample-hostname
      register: result
      
    - name: Reboot
      win_reboot:
      when: res.reboot_required
