---
- name:  Windows Update
  hosts: all
  gather_facts: false
  tasks:
  
  - name: Instaluje Java
    win_chocolatey:
      name: javaruntime
      state: present
  
    - name: Instauluje 7zip
      win_chocolatey:
        name: 7zip
        state: present

    - name: Installuje OpenOffice
      win_chocolatey:
        name: openoffice
        state: present

    - name: Instauluje AdobeReader
      win_chocolatey:
        name: adobereader
        state: present

    - name: Instaluje VLC
      win_chocolatey:
        name: vlc
        state: present

    - name: Instaluje FortiClientVPN
      win_chocolatey:
        name: forticlientvpn
        state: present



        
