---
- hosts: all
  gather_facts: false
  tasks:
    - name: Zakladam konto ansible
      win_user:
        name: ansible
        password: admin!123
        state: present
        password_never_expires: true
        groups:
          - Użytkownicy
          - Administratorzy
