---
- hosts: all
  gather_facts: false
  tasks:
    - name: Zakladam konto test
      win_user:
        name: test1
        password: admin!123
        state: present
        password_never_expires: true
        groups:
          - Użytkownicy
