---
- hosts: all
  gather_facts: false
  tasks:
    - name: Zakladam konto Ansible
      win_user:
        name: ansible
        password: admin!123
        state: present
        groups:
          - Administratorzy
