---
- hosts: all
  gather_facts: false
  tasks:
    - name: Zakladam konto ansible
      win_user:
        name: ansible
        password: admin!123
        state: present
        password_never_expires: true
        groups:
          - Użytkownicy
          - Administratorzy
          
    - name: Aktualizuje Windowsa
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      register: result
    - debug: var=result
       
    - win_reboot:
      when: result.reboot_required
 
    - name: Zmieniam nazwę hosta na v-win-awx4
      win_hostname:
        name: v-win-awx3
        register: result
            
    - name: Zakladam Katalog Software
      win_file:
        path: C:\Software
        state: directory   
      
    - name: Pobieram Ninite do katalogu Software
      win_get_url:
        url: https://ninite.com/7zip-firefox-malwarebytes-openoffice-putty-skype-teamviewer15-vlc/ninite.exe
        dest: C:\Software\ninite.exe
        
    - name: Instaluje Ninite z katalogu Software
      win_package:
        path: C:\Software\ninite.exe
        product_id: auto
        state: present
        
    - name: Reboot
      win_reboot:
