---
- hosts: all
  gather_facts: false
  tasks:
    - name: Katalog udostepniony
      win_share:
      # Nazwa katalogu w sieci
        name: test2
        description: Katalog udostepniony
        # Lokalizacja katalogu na komputerze (katalog musi istnieć)
        path: C:\shares\company1
        list: yes
        # Uprawnienia (per użytkownik)
        full: Admin
        read: ansible
