---
- name:  Windows Update
  hosts: all
  gather_facts: false
  tasks:
    - name: 7zip
      win_chocolatey:
        name: 7zip
        state: present

    - name: Install OpenOffice
      win_chocolatey:
        name: openoffice
        state: present

    - name: Adobe Reader
      win_chocolatey:
        name: adobereader
        state: present

    - name: Install VLC
      win_chocolatey:
        name: vlc
        state: present

    - name: Install forticlientvpn
      win_chocolatey:
        name: forticlientvpn
        state: present



        
