---
- name: Change the hostname to sample-hostname
  hosts: all
  gather_facts: false
  tasks: 
    - name: Change the hostname to sample-hostname
      win_hostname:
        name: v-win-awx
      register: result
      
    - name: Reboot
      win_reboot:
      when: result.reboot_required
